### PR TITLE
Add submission controller/route

### LINKED ISSUE #27: As tandem, I want to be alerted when someone sends us their calendars, so that we can begin scheduling.

### PR DESCRIPTION
**Pull request by thejinxters**
closes #27
This also adds bearer auth to all routes,
Also moves auth secret to the config file
Also creates config file for smtp.

I think we should wait on getting info and putting it into an email until we switch from mongoskin to mongojs (a more up-to-date and seemingly better wrapper for mongodb)

You will need to redefine your config file and npm install.

### CODE REVIEW

**Comment by Zandrr** [comment]
When I click sign out it doesn't do anything.  Is this supposed to work, or be a mock?

**Comment by thejinxters** [comment]
This should work, let me look into it...

**Comment by thejinxters** [comment]
@Zandrr I am not having that problem at all, The login/logout are both working great on my environment

**Comment by thejinxters** [comment]
Added the room links to the url by passing them through the frontend. It was simple and easy for this implementation, but we should change it up eventually so that server side is not reliant on anything frontend.

**Pull request merged**
